version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: personal-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5455:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
volumes:
  db:
    driver: local